### ISSUE TITLE
TypeError: this.queueTask is not a function

### ISSUE THREAD

**Issue by wdog** [EdRands/laravel-elixir-rename#2]
If you find this problem
`TypeError: this.queueTask is not a function`

maybe the solution is (i'm not an expert)

```php
var gulp = require('gulp');
var elixir = require('laravel-elixir');
var rename = require('gulp-rename');
/*
 |----------------------------------------------------------------
 | Rename Files
 |----------------------------------------------------------------
 |
 | A wrapper for gulp-rename. Makes renaming files easy.
 |
 */
var Task = elixir.Task;
elixir.extend('rename', function (input, options, output) {
    new Task('rename', function () {
        return gulp.src(input)
            .pipe(rename(options))
            .pipe(gulp.dest(output));
    });
});
```

**Comment by wdog** [comment]
I'll make a pull request

**Comment by phaberest** [comment]
Same issue here. I see you closed, what was the problem?

**Comment by EdRands** [comment]
Whoa! People besides me are using this? I made this for something I did quite a while ago, then stopped needing it.

I'm not currently setup for making this work with the latest version of Elixir, or testing it. Feel feel to make a pull request and I'll merge it,

**Comment by wdog** [comment]
there's no need to a new pull request just add a new tag because at the moment it's only on the master brench (I think :smile: )

**Comment by phaberest** [comment]
The problem is related to npm not pulling the latest version of the files. I git-pulled the repo files and placed them inside their node_modules folder and now everithing is working ;)

**Comment by EdRands** [comment]
Finally got on my butt and published a new version properly, which I never did before. You should be able to work fine with version 0.1.5.
